version: '3.9'

services:
  database:
    image: mariadb:10.6
    restart: always
    networks:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: catrame
      MYSQL_USER: giovanni
      MYSQL_PASSWORD: catrame
      MYSQL_DATABASE: giovanni
    volumes:
      - mariadb_data:/var/lib/mysql/

  phpmyadmin:
    image: phpmyadmin
    restart: always
    networks:
      - database
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
      PMA_USER: giovanni
      PMA_PASSWORD: catrame
  
  api:
    build:
      context: ./api
    restart: always
    networks:
      - database
    depends_on: 
      - nginx
    volumes:
      - api_deps_cache:/home/api/.cache/
  
  nginx:
    image: nginx:alpine
    networks: 
      - database
    ports:
      - 80:80
      - 443:443
    volumes: 
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    restart: always

networks:
  database:

volumes:
  mariadb_data:
  api_deps_cache:

