version: '3'

services:
  database:
    image: mariadb:10.6
    restart: always
    networks:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: catrame
      MYSQL_USER: giovanni
      MYSQL_PASSWORD: catrame
      MYSQL_DATABASE: giovanni
    volumes:
      - mariadb_data:/var/lib/mysql/

  phpmyadmin:
    image: phpmyadmin
    restart: always
    networks:
      - database
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
      PMA_USER: giovanni
      PMA_PASSWORD: catrame
  
  api:
    build:
      context: ./api
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    networks:
      - database
    ports:
      - 8000:8000
    volumes:
      - ./api/app:/usr/src/app/
    depends_on: 
      - database

  worker:
    build:
      context: ./worker
    restart: always
    networks:
      - database
    depends_on: 
      - api
  
  nginx:
    image: nginx:alpine
    networks: 
      - database
    ports:
      - 80:80
      - 443:443
    volumes: 
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - api
    restart: always

networks:
  database:

volumes:
  mariadb_data:
